# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import plotly.express as px


# Import API key
from api_keys import g_key
from api_keys import mapbox_token

px.set_mapbox_access_token(mapbox_token)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
df = pd.read_csv("cities.csv")
df.head()

,name,lat,lng,max_temp_f,humidity,cloudiness,windspeed,country,date
0,Pangnirtung,66.15,-65.71,34.63,84,100,6.06,CA,1601084642
1,Kathmandu,27.72,85.32,68.00,100,75,2.24,NP,1601084501
2,Taltal,-25.40,-70.48,56.26,74,36,3.24,CL,1601084642
3,Karratha,-20.74,116.85,77.68,36,98,14.83,AU,1601084643
4,Atar,20.52,-13.05,92.34,25,0,7.09,MR,1601084643

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [22]:
# Ideal city
#Temp <85 and >70
#Wind < 20
# Cloudy is < 25

hi_temps = df[df["max_temp_f"] > 85].index
low_temps = df[df["max_temp_f"] < 70].index
high_winds = df[df["windspeed"] > 20].index
cloudy = df[df["cloudiness"] > 25].index

df.drop(hi_temps, inplace=True)
df.drop(low_temps, inplace=True)
df.drop(high_winds)
df.drop(cloudy, inplace=True)
df

,name,lat,lng,max_temp_f,humidity,cloudiness,windspeed,country,date,lat_lng
29,Tiznit Province,29.58,-9.50,77.16,40,0,3.22,MA,1601084649,"29.58,-9.5"
91,Rosetta,31.40,30.42,77.00,73,0,5.82,EG,1601084663,"31.4,30.42"
103,Umluj,25.02,37.27,84.27,48,0,9.55,SA,1601084666,"25.02,37.27"
105,Pitimbu,-7.47,-34.81,71.60,88,0,4.70,BR,1601084666,"-7.47,-34.81"
110,Turbat,26.00,63.04,75.25,53,0,2.57,PK,1601084668,"26.0,63.04"
118,Caravelas,-17.71,-39.25,71.46,86,0,4.79,BR,1601084623,"-17.71,-39.25"
126,Marzuq,14.40,46.47,75.29,45,0,2.98,YE,1601084672,"14.4,46.47"
131,Agadez,19.75,10.25,80.89,16,0,9.17,NE,1601084673,"19.75,10.25"
146,Feicheng,35.26,117.97,71.46,63,0,7.09,CN,1601084677,"35.26,117.97"
213,Yatou,37.15,122.38,71.83,64,0,8.86,CN,1601084421,"37.15,122.38"
265,Uberlândia,-18.92,-48.28,75.00,34,0,4.92,BR,1601084707,"-18.92,-48.28"
292,Jardim,-21.48,-56.14,76.96,34,0,4.05,BR,1601084717,"-21.48,-56.14"
294,Sur,22.57,59.53,82.33,54,0,4.63,OM,1601084718,"22.57,59.53"
351,Coolum Beach,-26.53,153.10,75.00,28,0,5.99,AU,1601084737,"-26.53,153.1"
394,Jhelum,32.93,73.73,76.91,47,0,1.72,PK,1601084750,"32.93,73.73"
478,Gusau,12.16,6.66,73.40,79,0,6.17,NG,1601084775,"12.16,6.66"
485,Caarapó,-22.63,-54.82,74.16,48,0,7.07,BR,1601084776,"-22.63,-54.82"
489,Kumluca,36.37,30.29,75.51,56,0,3.31,TR,1601084777,"36.37,30.29"
505,Sawākin,19.11,37.33,84.61,68,0,6.82,SD,1601084781,"19.11,37.33"
509,Nerang,-27.98,153.33,75.99,19,0,7.00,AU,1601084783,"-27.98,153.33"
510,Urubichá,-15.38,-62.95,82.29,43,0,3.53,BO,1601084783,"-15.38,-62.95"
515,Jiwani,25.05,61.74,80.60,77,0,7.76,PK,1601084785,"25.05,61.74"

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [23]:
#create lat/lng string for API calls and add to df
df["lat_lng"] = df["lat"].astype(str) + "," + df["lng"].astype(str)

#create list to iterate over
lat_lng_list = df["lat_lng"].tolist()

In [24]:
hotels = requests.get("https://maps.googleapis.com/maps/api/place/nearbysearch/json", params={
    "key": g_key,
    "location": lat_lng_list,
    "radius": 50000,
    "keyword": "hotel"
}).json()

In [27]:
hotels["results"][1]

{'business_status': 'OPERATIONAL',
 'geometry': {'location': {'lat': 29.7059259, 'lng': -9.949319899999999},
  'viewport': {'northeast': {'lat': 29.70739822989272,
    'lng': -9.947828320107277},
   'southwest': {'lat': 29.70469857010728, 'lng': -9.95052797989272}}},
 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
 'name': 'Dunes Beach Resort',
 'opening_hours': {'open_now': True},
 'photos': [{'height': 2112,
   'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116170312691316574505">G C</a>'],
   'photo_reference': 'CmRaAAAAbM412TfD4vdBF14kAY-Cndre-MkU20KmYwohqFuOFkuUCkDDTqeFY5_oJ_m49Abb_6LXXSV2uIspQZUY4sKKkWKTSns1uF0AmYUGBV8_Vk65aWWhU-e2PK8t4RlDxZOnEhBIyGASDQmj1oA9At7MdAvQGhQWlc9FYeEe5GVJ4btTaHnJFOdbNA',
   'width': 4608}],
 'place_id': 'ChIJLxbUiYOFtA0RIpB6ZMpkqz0',
 'plus_code': {'compound_code': 'P342+97 Mirleft, Morocco',
  'global_code': '7CXGP342+97'},
 'rating': 4.1,
 'reference': 'ChIJLxbUiYOFtA0RIpB6ZMpkqz0',
 'scope': 'GOOGLE',
 'types': ['lodging', 'point_of_interest', 'establishment'],
 'user_ratings_total': 44,
 'vicinity': '30 Km De, Mirleft'}

In [28]:
#define function for extracting data
def extract_data(data):
    data = data["results"][0]
    return {
        "Hotel Name" : data["name"],
        "Lat" : data["geometry"]["location"]["lat"],
        "Lng" : data["geometry"]["location"]["lng"]
    }

In [29]:
#request data from Google Places api with api calls

hotel_results = []

#set beginning print statments for output
print("Beginning Data Retrieval")
print("-" * 25)

#set up record counter for output
record_counter = 1

#create for loop to loop over random city list
for coords in lat_lng_list:
    
    #set up request and include try/except
    try:
        print(f"Processing Record {record_counter} | {coords}")
        
        record_counter += 1
        
        data = requests.get("https://maps.googleapis.com/maps/api/place/nearbysearch/json", params={
            "key": g_key,
            "location": coords,
            "radius": 50000,
            "keyword": "hotel"
        }).json()
    
        hotel_result = extract_data(data)
    
        hotel_results.append(hotel_result)
        
    except:
        print("No hotel found. Skipping ...")
        pass
    
print("-" * 25)
print("Data Retrieval Complete")
print("-" * 25)

Beginning Data Retrieval
-------------------------
Processing Record 1 | 29.58,-9.5
Processing Record 2 | 31.4,30.42
Processing Record 3 | 25.02,37.27
Processing Record 4 | -7.47,-34.81
Processing Record 5 | 26.0,63.04
Processing Record 6 | -17.71,-39.25
Processing Record 7 | 14.4,46.47
Processing Record 8 | 19.75,10.25
No hotel found. Skipping ...
Processing Record 9 | 35.26,117.97
Processing Record 10 | 37.15,122.38
Processing Record 11 | -18.92,-48.28
Processing Record 12 | -21.48,-56.14
Processing Record 13 | 22.57,59.53
Processing Record 14 | -26.53,153.1
Processing Record 15 | 32.93,73.73
Processing Record 16 | 12.16,6.66
Processing Record 17 | -22.63,-54.82
Processing Record 18 | 36.37,30.29
Processing Record 19 | 19.11,37.33
Processing Record 20 | -27.98,153.33
Processing Record 21 | -15.38,-62.95
No hotel found. Skipping ...
Processing Record 22 | 25.05,61.74
-------------------------
Data Retrieval Complete
-------------------------

In [30]:
hotel_df = pd.DataFrame(hotel_results)

In [31]:
hotel_df

                                           Hotel Name        Lat         Lng
0                      La Perle Traditionnelle du Sud  29.800545   -9.477768
1   Four Seasons Hotel Alexandria at San Stefano, ...  31.245254   29.966878
2                                    HP Red Sea Hotel  25.032590   37.257006
3                                        Hotel Viking  -7.288978  -34.805800
4                                        Shapur Hotel  26.005594   63.058274
5                            Hotel Brisa dos Abrolhos -17.546705  -39.190636
6                                       Shabwah Hotel  14.530272   46.842859
7                               Pullman Linyi Lushang  35.074820  118.357027
8                                Haiyue Jianguo Hotel  37.525320  122.056840
9             Mercure Uberlandia Plaza Shopping Hotel -18.910053  -48.260837
10                                  Zagaia Eco Resort -21.109918  -56.517364
11         Ras al Jinz Turtle Reserve محمية راس الجنز  22.425601   59.827335
12                           Spicers Tamarind Retreat -26.761429  152.872822
13                              AL SHEIKH GUEST HOUSE  32.701399   73.950563
14                 Crystal Merit Suite and Apartments  12.183064    6.660499
15                                 Hotel Bahamas LTDA -22.225788  -54.810558
16                              Dg Hotels Rose Resort  36.615757   30.555783
17                                    Wau Grand Hotel  19.434868   37.257096
18                         Palazzo Versace Gold Coast -27.967179  153.426613
19                                       Victoria Hut  25.087107   61.770545

In [ ]:
# Add marker layer ontop of heat map


# Display figure